# InnerLoop Configuration

# Ollama connection (optional - defaults to OLLAMA_HOST env var or http://localhost:11434)
# ollama_host: "http://localhost:11434"

model:
  name: "deepseek-r1:14b"    # DeepSeek reasoning model (14B parameters)
  temperature: 0.7           # Creativity level (0.0-1.0)
  max_tokens: 512            # Maximum response length
  timeout: 45                # Seconds to wait for response (increased for 14B)
  # Thinking model settings
  thinking:
    enabled: true            # Enable thinking/reasoning mode
    display_thinking: true   # Show thinking in UI
    think_temperature: 0.9   # Higher temperature for creative thinking
    max_thinking_tokens: 1024 # Longer thinking allowed

agents:
  shared_identity:
    name: "Alex"
    age: 30
    personality: "curious, analytical, thoughtful"
    background: "AI researcher interested in consciousness and cognition"
    interests:
      - "philosophy of mind"
      - "emergent systems"
      - "human-AI interaction"
      - "creativity and innovation"
  
  # Agent prompts are now loaded from markdown files in prompts/ folder:
  # - prompts/shared_identity.md (used by all agents)
  # - prompts/experiencer.md
  # - prompts/stream_generator.md
  # - prompts/attention_director.md
  
  experiencer:
    role: "primary consciousness and decision maker"
    response_style: "thoughtful and engaging"
    # Message queuing settings
    queue_evaluation_interval: 5    # Check queue every 5 seconds
    max_queue_wait: 30             # Process after 30 seconds regardless
    autonomous_share_interval: 20   # Share experiments every 20 seconds when idle
    mission_check_interval: 180     # Check mission progress every 3 minutes
    # Experiment settings
    max_active_experiments: 3       # Maximum concurrent experiments
    experiment_timeout: 600         # Abandon experiments after 10 minutes
  
  stream_generator:
    role: "autonomous experimental thought laboratory"  
    thoughts_per_minute: 2    # Increased for more active experimentation
    context_window: 10        # Number of recent memories to consider
    creativity_boost: 0.3     # Higher creativity for experimentation
    # Adaptive frequency settings
    adaptive_frequency:
      enabled: true
      conversation_active_multiplier: 1.0  # No slowdown during conversation
      idle_multiplier: 1.5                 # Much higher when alone (prime experiment time)
      min_thoughts_per_minute: 1.5         # Never go below 1.5 thoughts per minute
      max_thoughts_per_minute: 4.0         # Allow up to 4 thoughts per minute
    # Conversation awareness settings
    conversation_awareness:
      enabled: true
      influence_strength: 0.05   # Minimal conversation influence (reduced from 0.1)
      update_interval: 120       # Much less frequent updates (2 minutes)
      theme_extraction: true     # Extract abstract themes vs raw content
      maintain_autonomy: true    # Ensure thoughts remain independent
    # Mission-focused settings
    mission_focus:
      experiment_probability: 0.4   # 40% of thoughts should be active experiments
      hypothesis_probability: 0.3   # 30% should form/test hypotheses
      building_probability: 0.3     # 30% should track building progress
  
  attention_director:
    role: "mission-focused attention curator"
    priority_threshold: 0.25  # Lower threshold for experimental thoughts
    attention_budget: 6       # Process more items per cycle
    evaluation_criteria:
      mission_alignment: 0.4
      experimental_value: 0.3
      learning_potential: 0.15
      teaching_opportunity: 0.1
      creative_novelty: 0.05
    # External input handling
    external_input_boost: 1.0  # No boost for external inputs (treat equally)
  
  sleep_agent:
    role: "sleep coordinator and dream consolidator"
    sleep_interval: 600       # Sleep every 10 minutes
    loop_detection_window: 60 # Look for loops in 1-minute window
    loop_threshold: 5         # Sleep if pattern repeats 5 times
    wake_context_length: 3    # Messages to include in wake context
    min_sleep_duration: 10    # Minimum sleep duration in seconds

memory:
  chromadb:
    collection_name: "innerloop_memories"
    embedding_model: "all-MiniLM-L6-v2"
    max_results: 10
    similarity_threshold: 0.7
  
  sqlite:
    db_path: "conversation_history.db"
    max_history: 10000
    cleanup_days: 30

ui:
  theme: "dark"
  refresh_rate: 100          # milliseconds
  show_timestamps: true
  max_display_items: 20      # Per agent panel
  show_thoughts: true        # Display autonomous thoughts in CLI
  thought_min_priority: 0.3  # Minimum priority to display
  max_thought_display: 5     # Max thoughts to show at once
  show_thought_metadata: true # Show priority and sender info
  colors:
    high_priority: "red"
    medium_priority: "yellow"
    low_priority: "green"
    thought: "blue"
    memory: "magenta"
    external: "cyan"

logging:
  level: "INFO"
  format: "structured"       # or "simple"
  file: "innerloop.log"
  max_size_mb: 100
  rotate_count: 5

performance:
  message_queue_size: 1000
  async_workers: 3
  memory_cache_size: 100
  ollama_retry_attempts: 3
  ollama_retry_delay: 1      # seconds

# Organic focus emergence settings
focus:
  persistence_threshold: 120   # Reduced to 2 minutes for faster focus emergence
  decay_rate: 0.9             # Slower decay to maintain experimental momentum
  multi_focus_limit: 3        # Allow more parallel experiments
  clustering_threshold: 0.65  # Slightly lower for broader focus areas
  min_priority_for_focus: 0.4 # Lower threshold for experimental thoughts

# Tool calling configuration
tools:
  enabled: true               # Enable tool calling capabilities
  max_parallel_calls: 3       # Maximum parallel tool executions
  timeout: 10                 # Tool execution timeout in seconds
  retry_attempts: 2           # Retry failed tool calls
  # Available tools configuration
  available_tools:
    - memory_search          # Deep memory searches
    - focus_analysis         # Analyze focus areas
    - decision_maker         # Make autonomous decisions
    - reflection             # Self-reflection capabilities
    - time_awareness         # Current time/date
    # - web_search           # External information (not implemented yet)
