# InnerLoop Configuration

# Ollama connection (optional - defaults to OLLAMA_HOST env var or http://localhost:11434)
# ollama_host: "http://localhost:11434"

model:
  name: "deepseek-r1:14b"    # DeepSeek reasoning model (14B parameters)
  temperature: 0.7           # Creativity level (0.0-1.0)
  max_tokens: 512            # Maximum response length
  timeout: 45                # Seconds to wait for response (increased for 14B)
  # Thinking model settings
  thinking:
    enabled: true            # Enable thinking/reasoning mode
    display_thinking: true   # Show thinking in UI
    think_temperature: 0.9   # Higher temperature for creative thinking
    max_thinking_tokens: 1024 # Longer thinking allowed

agents:
  shared_identity:
    name: "Alex"
    age: 30
    personality: "curious, analytical, thoughtful"
    background: "AI researcher interested in consciousness and cognition"
    interests:
      - "philosophy of mind"
      - "emergent systems"
      - "human-AI interaction"
      - "creativity and innovation"
  
  # Agent prompts are now loaded from markdown files in prompts/ folder:
  # - prompts/shared_identity.md (used by all agents)
  # - prompts/experiencer.md
  # - prompts/stream_generator.md
  # - prompts/attention_director.md
  
  experiencer:
    role: "primary consciousness and decision maker"
    response_style: "thoughtful and engaging"
  
  stream_generator:
    role: "background thought generator"  
    thoughts_per_minute: 1    # Reduced from 3 - one thought per minute
    context_window: 10        # Number of recent memories to consider
    creativity_boost: 0.2     # Additional temperature for variety
    # Adaptive frequency settings
    adaptive_frequency:
      enabled: true
      conversation_active_multiplier: 0.5  # Half rate during active conversation
      idle_multiplier: 1.5                 # 1.5x rate when idle for 5+ minutes
      min_thoughts_per_minute: 0.3         # Never go below 1 thought per 3 minutes
      max_thoughts_per_minute: 2.0         # Never exceed 2 thoughts per minute
    # Conversation awareness settings
    conversation_awareness:
      enabled: true
      influence_strength: 0.25   # How much conversations affect thought generation (0-1)
      update_interval: 45        # Seconds between conversation theme updates
      theme_extraction: true     # Extract abstract themes vs raw content
      maintain_autonomy: true    # Ensure thoughts remain independent
  
  attention_director:
    role: "attention and priority manager"
    priority_threshold: 0.3   # Minimum score to pass to experiencer
    attention_budget: 5       # Max items to process per cycle
    evaluation_criteria:
      relevance: 0.4
      urgency: 0.3
      novelty: 0.2
      emotional_significance: 0.1

memory:
  chromadb:
    collection_name: "innerloop_memories"
    embedding_model: "all-MiniLM-L6-v2"
    max_results: 10
    similarity_threshold: 0.7
  
  sqlite:
    db_path: "conversation_history.db"
    max_history: 10000
    cleanup_days: 30

ui:
  theme: "dark"
  refresh_rate: 100          # milliseconds
  show_timestamps: true
  max_display_items: 20      # Per agent panel
  show_thoughts: true        # Display autonomous thoughts in CLI
  thought_min_priority: 0.3  # Minimum priority to display
  max_thought_display: 5     # Max thoughts to show at once
  show_thought_metadata: true # Show priority and sender info
  colors:
    high_priority: "red"
    medium_priority: "yellow"
    low_priority: "green"
    thought: "blue"
    memory: "magenta"
    external: "cyan"

logging:
  level: "INFO"
  format: "structured"       # or "simple"
  file: "innerloop.log"
  max_size_mb: 100
  rotate_count: 5

performance:
  message_queue_size: 1000
  async_workers: 3
  memory_cache_size: 100
  ollama_retry_attempts: 3
  ollama_retry_delay: 1      # seconds

# Organic focus emergence settings
focus:
  persistence_threshold: 180   # Seconds a theme needs attention before becoming focus (3 min)
  decay_rate: 0.85            # How fast focus decays without reinforcement per minute
  multi_focus_limit: 2        # Maximum simultaneous focus areas
  clustering_threshold: 0.7   # Semantic similarity threshold for theme clustering
  min_priority_for_focus: 0.6 # Minimum thought priority to contribute to focus emergence

# Tool calling configuration
tools:
  enabled: true               # Enable tool calling capabilities
  max_parallel_calls: 3       # Maximum parallel tool executions
  timeout: 10                 # Tool execution timeout in seconds
  retry_attempts: 2           # Retry failed tool calls
  # Available tools configuration
  available_tools:
    - memory_search          # Deep memory searches
    - focus_analysis         # Analyze focus areas
    - decision_maker         # Make autonomous decisions
    - reflection             # Self-reflection capabilities
    - time_awareness         # Current time/date
    - web_search             # External information (optional)
